### ISSUE TITLE
macOS type cast exception

### ISSUE THREAD

**Issue by andrikeev** [incrediblezayed/file_saver#3] opened 2021-04-18 10:18 UTC
On macOS there is error:

```
type 'Future<Directory?>' is not a subtype of type 'FutureOr<Directory>' in type cast
```

I guess it is in `_getDirectory` method:
```
if (Platform.isMacOS) {
    _path = (await (path.getDownloadsDirectory() as FutureOr<Directory>)).path;
}
```

**Comment by incrediblezayed** [comment] 2021-07-05 12:15
The issue is fixed now, please check the latest version.

**Closed by incrediblezayed** 2021-07-05 12:15 UTC
