### ISSUE TITLE
Passing bytes parameter not working as expected

### ISSUE THREAD

**Issue by fuzzball1980** [incrediblezayed/file_saver#58] opened 2023-05-04 02:50 UTC
Hi guys! Passing the bytes parameter still gets the assertion 

  String? savedPath = await FileSaver.instance.saveAs(
      name: "fileNameXXX.file",
      bytes: fileContent,
      ext: "file",
      mimeType: MimeType.other);

filePath != null || link != null || file != null
"Either filePath or link or file must be provided"

**Comment by incrediblezayed** [comment] 2023-05-09 14:08
Hi @fuzzball1980, Can you help me reproduce the issue, because I can save the file without any issue

**Comment by incrediblezayed** [comment] 2023-05-09 14:10
> Hi guys! Passing the bytes parameter still gets the assertion
> 
> String? savedPath = await FileSaver.instance.saveAs( name: "fileNameXXX.file", bytes: fileContent, ext: "file", mimeType: MimeType.other);
> 
> filePath != null || link != null || file != null "Either filePath or link or file must be provided"

Mostly the bytes you are passing in the parameter might be null, please check at your end, I'm closing the issue now, please reopen if this doesn't solves your issue.

**Closed by incrediblezayed** 2023-05-09 14:10 UTC
